/* overlay.c -- on-screen FPS / frame-time overlay drawn in the eglSwapBuffers
 * hook, plus frame-time spike logging.
 *
 * Copyright (C) 2021 fgsfds, Andy Nguyen
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 * The original version of this file only printed a 1-second average FPS to
 * the log. A 1-second average cannot show a freeze: a single 880ms stall
 * inside a second still averages out to a plausible-looking number, which is
 * exactly the failure this port is being tuned against. This version tracks
 * every frame's wall time, draws it on screen, and logs each individual spike
 * together with the streaming work charged to that frame.
 *
 * The font atlas (font_atlas.h, Consolas Bold 34px, 8bpp alpha) was already
 * generated by analysis/gen_font.py but had no renderer; this supplies one.
 */

#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <EGL/egl.h>
#include <GLES2/gl2.h>
#include <switch.h>

#include "config.h"
#include "util.h"
#include "overlay.h"
#include "movie.h"
#include "font_atlas.h"

extern uint32_t g_frame_count;

/* Streaming work attributed to the frame just finished; read-and-reset, so
 * the accumulator's frame boundary is this hook. Defined in hooks/game.c. */
extern void gta3_take_frame_stream_stats(double *out_total_ms, int *out_worst_index,
                                         double *out_worst_ms);

/* A frame is "slow" when it overruns the 30fps budget by a clear margin, and
 * a "freeze" when it is long enough to read as a visible hitch rather than a
 * single dropped frame. Both are logged; only freezes are counted on screen. */
#define SLOW_FRAME_MS   50.0
#define FREEZE_FRAME_MS 100.0

/* How long the on-screen peak lingers before it decays, in seconds. */
#define WORST_WINDOW_SEC 3

static float current_fps = 0.0f;
static double last_frame_ms = 0.0;
static double worst_recent_ms = 0.0;
static uint32_t freeze_count = 0;
static uint32_t slow_count = 0;

static u64 last_ticks = 0;
static u64 fps_window_start = 0;
static int fps_window_frames = 0;
static u64 worst_recent_tick = 0;

/* ---------------- GLES2 text renderer ---------------- */

static const char *kVertSrc =
  "attribute vec2 aPos;\n"
  "attribute vec2 aUV;\n"
  "varying vec2 vUV;\n"
  "uniform vec2 uInvSize;\n"
  "void main() {\n"
  "  vUV = aUV;\n"
  "  vec2 p = aPos * uInvSize;\n"
  "  gl_Position = vec4(p.x * 2.0 - 1.0, 1.0 - p.y * 2.0, 0.0, 1.0);\n"
  "}\n";

static const char *kFragSrc =
  "precision mediump float;\n"
  "varying vec2 vUV;\n"
  "uniform sampler2D uTex;\n"
  "uniform vec4 uColor;\n"
  "uniform float uUseTex;\n"
  "void main() {\n"
  "  float a = mix(1.0, texture2D(uTex, vUV).a, uUseTex);\n"
  "  gl_FragColor = vec4(uColor.rgb, uColor.a * a);\n"
  "}\n";

static GLuint prog = 0, tex = 0;
static GLint loc_pos = -1, loc_uv = -1, loc_invsize = -1;
static GLint loc_tex = -1, loc_color = -1, loc_usetex = -1;
static bool gl_init_failed = false;

#define MAX_QUADS 160
static GLfloat verts[MAX_QUADS * 6 * 4]; /* 6 verts/quad, (x,y,u,v) */
static int vert_count = 0;

static GLuint compile_shader(GLenum type, const char *src) {
  GLuint sh = glCreateShader(type);
  if (!sh) return 0;
  glShaderSource(sh, 1, &src, NULL);
  glCompileShader(sh);
  GLint ok = 0;
  glGetShaderiv(sh, GL_COMPILE_STATUS, &ok);
  if (!ok) {
    char log[512];
    GLsizei n = 0;
    glGetShaderInfoLog(sh, sizeof(log) - 1, &n, log);
    log[n] = 0;
    debugPrintf("[OVERLAY] shader compile failed: %s\n", log);
    glDeleteShader(sh);
    return 0;
  }
  return sh;
}

static bool overlay_gl_init(void) {
  if (prog) return true;
  if (gl_init_failed) return false;

  GLuint vs = compile_shader(GL_VERTEX_SHADER, kVertSrc);
  GLuint fs = compile_shader(GL_FRAGMENT_SHADER, kFragSrc);
  if (!vs || !fs) { gl_init_failed = true; return false; }

  prog = glCreateProgram();
  glAttachShader(prog, vs);
  glAttachShader(prog, fs);
  glLinkProgram(prog);
  glDeleteShader(vs);
  glDeleteShader(fs);

  GLint ok = 0;
  glGetProgramiv(prog, GL_LINK_STATUS, &ok);
  if (!ok) {
    debugPrintf("[OVERLAY] program link failed\n");
    glDeleteProgram(prog);
    prog = 0;
    gl_init_failed = true;
    return false;
  }

  loc_pos     = glGetAttribLocation(prog, "aPos");
  loc_uv      = glGetAttribLocation(prog, "aUV");
  loc_invsize = glGetUniformLocation(prog, "uInvSize");
  loc_tex     = glGetUniformLocation(prog, "uTex");
  loc_color   = glGetUniformLocation(prog, "uColor");
  loc_usetex  = glGetUniformLocation(prog, "uUseTex");
  if (loc_pos < 0 || loc_uv < 0) { gl_init_failed = true; return false; }

  glGenTextures(1, &tex);
  glBindTexture(GL_TEXTURE_2D, tex);
  glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
  glTexImage2D(GL_TEXTURE_2D, 0, GL_ALPHA, FONT_ATLAS_W, FONT_ATLAS_H, 0,
               GL_ALPHA, GL_UNSIGNED_BYTE, font_atlas);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);

  debugPrintf("[OVERLAY] GL text renderer initialized (atlas %dx%d)\n",
              FONT_ATLAS_W, FONT_ATLAS_H);
  return true;
}

static void push_quad(float x0, float y0, float x1, float y1,
                      float u0, float v0, float u1, float v1) {
  if (vert_count + 6 > MAX_QUADS * 6) return;
  GLfloat *v = &verts[vert_count * 4];
  const GLfloat q[6][4] = {
    { x0, y0, u0, v0 }, { x1, y0, u1, v0 }, { x0, y1, u0, v1 },
    { x1, y0, u1, v0 }, { x1, y1, u1, v1 }, { x0, y1, u0, v1 },
  };
  memcpy(v, q, sizeof(q));
  vert_count += 6;
}

static void push_text(const char *s, float x, float y, float scale) {
  const float cw = FONT_CELL_W * scale;
  const float ch = FONT_CELL_H * scale;
  const float du = (float)FONT_CELL_W / (float)FONT_ATLAS_W;
  const float dv = (float)FONT_CELL_H / (float)FONT_ATLAS_H;
  for (const unsigned char *p = (const unsigned char *)s; *p; p++) {
    int idx = (int)(*p) - FONT_FIRST;
    if (idx >= 0 && idx < FONT_COUNT && *p != ' ') {
      float u0 = (float)(idx % FONT_COLS) * du;
      float v0 = (float)(idx / FONT_COLS) * dv;
      push_quad(x, y, x + cw, y + ch, u0, v0, u0 + du, v0 + dv);
    }
    x += cw;
  }
}

/* Draws the accumulated quads. The game is mid-render, so every piece of GL
 * state this touches is saved first and restored afterwards. */
static void flush_quads(float sw, float sh, float r, float g, float b, float a,
                        float use_tex) {
  if (vert_count == 0) return;

  GLint old_prog = 0, old_abuf = 0, old_tex = 0, old_active = 0;
  GLint old_vp[4];
  GLint old_sfac = 0, old_dfac = 0;
  GLint a0_en = 0, a1_en = 0;
  GLboolean old_blend, old_depth, old_cull, old_scissor;

  glGetIntegerv(GL_CURRENT_PROGRAM, &old_prog);
  glGetIntegerv(GL_ARRAY_BUFFER_BINDING, &old_abuf);
  glGetIntegerv(GL_ACTIVE_TEXTURE, &old_active);
  glGetIntegerv(GL_VIEWPORT, old_vp);
  glGetIntegerv(GL_BLEND_SRC_ALPHA, &old_sfac);
  glGetIntegerv(GL_BLEND_DST_ALPHA, &old_dfac);
  old_blend   = glIsEnabled(GL_BLEND);
  old_depth   = glIsEnabled(GL_DEPTH_TEST);
  old_cull    = glIsEnabled(GL_CULL_FACE);
  old_scissor = glIsEnabled(GL_SCISSOR_TEST);

  glActiveTexture(GL_TEXTURE0);
  glGetIntegerv(GL_TEXTURE_BINDING_2D, &old_tex);
  glGetVertexAttribiv(loc_pos, GL_VERTEX_ATTRIB_ARRAY_ENABLED, &a0_en);
  glGetVertexAttribiv(loc_uv,  GL_VERTEX_ATTRIB_ARRAY_ENABLED, &a1_en);

  glUseProgram(prog);
  glBindBuffer(GL_ARRAY_BUFFER, 0); /* client-side arrays below */
  glViewport(0, 0, (GLsizei)sw, (GLsizei)sh);
  glDisable(GL_DEPTH_TEST);
  glDisable(GL_CULL_FACE);
  glDisable(GL_SCISSOR_TEST);
  glEnable(GL_BLEND);
  glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

  glBindTexture(GL_TEXTURE_2D, tex);
  glUniform1i(loc_tex, 0);
  glUniform2f(loc_invsize, 1.0f / sw, 1.0f / sh);
  glUniform4f(loc_color, r, g, b, a);
  glUniform1f(loc_usetex, use_tex);

  glEnableVertexAttribArray(loc_pos);
  glEnableVertexAttribArray(loc_uv);
  glVertexAttribPointer(loc_pos, 2, GL_FLOAT, GL_FALSE, 4 * sizeof(GLfloat), verts);
  glVertexAttribPointer(loc_uv,  2, GL_FLOAT, GL_FALSE, 4 * sizeof(GLfloat), verts + 2);
  glDrawArrays(GL_TRIANGLES, 0, vert_count);

  if (!a0_en) glDisableVertexAttribArray(loc_pos);
  if (!a1_en) glDisableVertexAttribArray(loc_uv);
  glBindTexture(GL_TEXTURE_2D, (GLuint)old_tex);
  glActiveTexture((GLenum)old_active);
  glBindBuffer(GL_ARRAY_BUFFER, (GLuint)old_abuf);
  glUseProgram((GLuint)old_prog);
  glViewport(old_vp[0], old_vp[1], old_vp[2], old_vp[3]);
  glBlendFunc((GLenum)old_sfac, (GLenum)old_dfac);
  if (!old_blend)  glDisable(GL_BLEND);
  if (old_depth)   glEnable(GL_DEPTH_TEST);
  if (old_cull)    glEnable(GL_CULL_FACE);
  if (old_scissor) glEnable(GL_SCISSOR_TEST);

  vert_count = 0;
}

static void draw_overlay(void *display, void *surface) {
  if (!overlay_gl_init()) return;

  /* Same trap the movie player fell into: eglQuerySurface keeps reporting the
   * window's default 1280x720 after nwindowSetDimensions has resized it, so
   * docked it under-reports a 1920x1080 surface. flush_quads() turns this into
   * a glViewport, which put the whole overlay inside the bottom-left two thirds
   * of the screen. screen_width/screen_height is the size the engine's own
   * viewport agrees with. */
  EGLint egl_w = 0, egl_h = 0;
  eglQuerySurface((EGLDisplay)display, (EGLSurface)surface, EGL_WIDTH, &egl_w);
  eglQuerySurface((EGLDisplay)display, (EGLSurface)surface, EGL_HEIGHT, &egl_h);

  int w = screen_width, h = screen_height;
  if (w <= 0 || h <= 0) {
    w = (egl_w > 0) ? egl_w : 1280;
    h = (egl_h > 0) ? egl_h : 720;
  }

  char l1[64], l2[64], l3[64];
  snprintf(l1, sizeof(l1), "FPS %.0f  %.1fms", current_fps, last_frame_ms);
  snprintf(l2, sizeof(l2), "PEAK %.0fms  FRZ %u/%u", worst_recent_ms,
           freeze_count, slow_count);

  /* Third line reports the size actually being rendered at. The dock state is
   * queried every frame because it can change at any moment, and the two
   * together are what make a frame-rate number comparable between runs --
   * 1280x720 handheld and 1920x1080 docked are very different amounts of
   * work. */
  const bool docked = (appletGetOperationMode() == AppletOperationMode_Console);
  snprintf(l3, sizeof(l3), "%dx%d  %s", (int)w, (int)h, docked ? "DOCKED" : "HANDHELD");

  const float scale = 0.55f;
  const float pad = 8.0f;
  const float lh = FONT_CELL_H * scale;

  size_t longest = strlen(l1);
  if (strlen(l2) > longest) longest = strlen(l2);
  if (strlen(l3) > longest) longest = strlen(l3);
  const float tw = (float)longest * FONT_CELL_W * scale;

  /* Backing panel first, so the text stays readable over bright scenery. */
  push_quad(pad - 4.0f, pad - 4.0f, pad + tw + 4.0f, pad + lh * 3.0f + 4.0f,
            0.0f, 0.0f, 0.0f, 0.0f);
  flush_quads((float)w, (float)h, 0.0f, 0.0f, 0.0f, 0.55f, 0.0f);

  push_text(l1, pad, pad, scale);
  flush_quads((float)w, (float)h, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f);

  /* Second line turns red once anything has actually frozen this session. */
  push_text(l2, pad, pad + lh, scale);
  if (freeze_count > 0)
    flush_quads((float)w, (float)h, 1.0f, 0.35f, 0.25f, 1.0f, 1.0f);
  else
    flush_quads((float)w, (float)h, 0.75f, 0.85f, 0.75f, 1.0f, 1.0f);

  /* Third line is context, not a warning, so it stays dimmer than the rest. */
  push_text(l3, pad, pad + lh * 2.0f, scale);
  flush_quads((float)w, (float)h, 0.65f, 0.75f, 0.95f, 1.0f, 1.0f);
}

unsigned int eglSwapBuffersHook(void *display, void *surface) {
  u64 now = armGetSystemTick();
  u64 freq = armGetSystemTickFreq();

  if (last_ticks == 0) {
    last_ticks = now;
    fps_window_start = now;
    worst_recent_tick = now;
  }

  double dt_ms = (double)(now - last_ticks) * 1000.0 / (double)freq;
  last_ticks = now;
  last_frame_ms = dt_ms;

  /* Rolling FPS over a short window -- short enough to react, long enough not
   * to jitter. Deliberately separate from the spike reporting below, which is
   * per-frame precisely because averaging is what hid these stalls before. */
  fps_window_frames++;
  if (now - fps_window_start >= freq / 2) {
    current_fps = (float)fps_window_frames * (float)freq /
                  (float)(now - fps_window_start);
    fps_window_frames = 0;
    fps_window_start = now;
  }

  if (dt_ms > worst_recent_ms || now - worst_recent_tick >= freq * WORST_WINDOW_SEC) {
    worst_recent_ms = dt_ms;
    worst_recent_tick = now;
  }

  /* Read-and-reset every frame regardless of whether this one spiked, so the
   * accumulator always covers exactly one frame and a stall is never credited
   * to a later frame that happened to be the one that crossed the threshold. */
  double stream_ms = 0.0, worst_ms = 0.0;
  int worst_index = -1;
  gta3_take_frame_stream_stats(&stream_ms, &worst_index, &worst_ms);

  if (dt_ms >= SLOW_FRAME_MS) {
    slow_count++;
    bool is_freeze = (dt_ms >= FREEZE_FRAME_MS);
    if (is_freeze) freeze_count++;

    debugPrintf("[PERF_%s] frame #%u dt=%.1fms (fps=%.1f) stream=%.1fms "
                "worst_index=%d (%.1fms) unaccounted=%.1fms\n",
                is_freeze ? "FREEZE" : "HITCH", g_frame_count, dt_ms,
                current_fps, stream_ms, worst_index, worst_ms,
                dt_ms - stream_ms);
  }

  /* An intro movie owns the whole frame while it plays, so it goes down first
   * and the FPS overlay stays on top of it. */
  movie_render(display, surface);

  if (config.show_fps_overlay)
    draw_overlay(display, surface);

  return eglSwapBuffers((EGLDisplay)display, (EGLSurface)surface);
}
